### PR TITLE
add credit for icon.png

### PR DESCRIPTION
**Pull request by FlameKat53**
This adds icon.png (Wii U Shell) removes icon.jpg (NX-Shell)
and I added myself some
Credits

### CODE REVIEW

**Comment by FlameKat53** [comment]
I will PR when I add icon.png

**Comment by FlameKat53** [comment]
I added icon.png

**Comment by danch15** [comment]
https://github.com/joel16/NX-Shell/releases
Hello, rw-r-r-0644, the NX-Shell had update to 1.2, it supported to copy file from SD Card to the Nand or the USB Device, can you sync the code, thank you very much.

(wupclient.py, 
ret = w.cpdir("/vol/storage_sdcard/sdcafiine/0005000e10101c00/content", "/vol/storage_mlc01/usr/title/0005000e/10101c00/content/")
ret = w.cpdir("/vol/storage_sdcard/sdcafiine/0005000c10101c00/aoc", "/vol/storage_usb01/usr/title/0005000c/10101c00/content/")
)

**Comment by rw-r-r-0644** [comment]
@FlameKat53 Thank you for the icon! I merged the changes

@danch15 We have been working on an accelerated SDL2 renderer, which should make the app quite a lot faster, though unfortunately there seem to be some issues with some apps including this one. After that issue is fixed I'll try syncing the code and adding some changes for nand/usb access on the Wii U

**Pull request merged**
